// Action Types
export const SET_SELECTED_COURSE = 'SET_SELECTED_COURSE'
export const SET_SELECTED_SEMESTER = 'SET_SELECTED_SEMESTER'
export const SET_PROFESSOR = 'SET_PROFESSOR'
export const SET_COURSES = 'SET_COURSES'
export const SET_SEMESTERS = 'SET_SEMESTERS'


