// flow-typed signature: 6e5993ffbe9f8270455ed0b67103d22f
// flow-typed version: <<STUB>>/gulp-livereload_v^3.8.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-livereload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-livereload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-livereload/examples/basepath' {
  declare module.exports: any;
}

declare module 'gulp-livereload/examples/custom-port' {
  declare module.exports: any;
}

declare module 'gulp-livereload/examples/https' {
  declare module.exports: any;
}

declare module 'gulp-livereload/examples/nodemon/app' {
  declare module.exports: any;
}

declare module 'gulp-livereload/examples/nodemon/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-livereload/examples/nodemon/index' {
  declare module.exports: any;
}

declare module 'gulp-livereload/examples/static-server' {
  declare module.exports: any;
}

declare module 'gulp-livereload/examples/watch' {
  declare module.exports: any;
}

declare module 'gulp-livereload/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-livereload/examples/basepath.js' {
  declare module.exports: $Exports<'gulp-livereload/examples/basepath'>;
}
declare module 'gulp-livereload/examples/custom-port.js' {
  declare module.exports: $Exports<'gulp-livereload/examples/custom-port'>;
}
declare module 'gulp-livereload/examples/https.js' {
  declare module.exports: $Exports<'gulp-livereload/examples/https'>;
}
declare module 'gulp-livereload/examples/nodemon/app.js' {
  declare module.exports: $Exports<'gulp-livereload/examples/nodemon/app'>;
}
declare module 'gulp-livereload/examples/nodemon/gulpfile.js' {
  declare module.exports: $Exports<'gulp-livereload/examples/nodemon/gulpfile'>;
}
declare module 'gulp-livereload/examples/nodemon/index.js' {
  declare module.exports: $Exports<'gulp-livereload/examples/nodemon/index'>;
}
declare module 'gulp-livereload/examples/static-server.js' {
  declare module.exports: $Exports<'gulp-livereload/examples/static-server'>;
}
declare module 'gulp-livereload/examples/watch.js' {
  declare module.exports: $Exports<'gulp-livereload/examples/watch'>;
}
declare module 'gulp-livereload/index' {
  declare module.exports: $Exports<'gulp-livereload'>;
}
declare module 'gulp-livereload/index.js' {
  declare module.exports: $Exports<'gulp-livereload'>;
}
declare module 'gulp-livereload/test/index.js' {
  declare module.exports: $Exports<'gulp-livereload/test/index'>;
}
