// flow-typed signature: 82876390ecd2f2fac2f063ff1b0ddc39
// flow-typed version: <<STUB>>/gx_v^1.0.0-rc3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gx/dist/Gx' {
  declare module.exports: any;
}

declare module 'gx/docs/data' {
  declare module.exports: any;
}

declare module 'gx/docs/Root' {
  declare module.exports: any;
}

declare module 'gx/src/Gx' {
  declare module.exports: any;
}

declare module 'gx/test/index' {
  declare module.exports: any;
}

declare module 'gx/test/karma.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gx/dist/Gx.js' {
  declare module.exports: $Exports<'gx/dist/Gx'>;
}
declare module 'gx/docs/data.js' {
  declare module.exports: $Exports<'gx/docs/data'>;
}
declare module 'gx/docs/Root.js' {
  declare module.exports: $Exports<'gx/docs/Root'>;
}
declare module 'gx/src/Gx.js' {
  declare module.exports: $Exports<'gx/src/Gx'>;
}
declare module 'gx/test/index.js' {
  declare module.exports: $Exports<'gx/test/index'>;
}
declare module 'gx/test/karma.config.js' {
  declare module.exports: $Exports<'gx/test/karma.config'>;
}
