// flow-typed signature: d444b5c6a4b949df6cf168e00ebb56d5
// flow-typed version: <<STUB>>/node-jsx_v^0.13.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-jsx/node-jsx.spec' {
  declare module.exports: any;
}

declare module 'node-jsx/test-module' {
  declare module.exports: any;
}

declare module 'node-jsx/test-sourcemap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-jsx/index' {
  declare module.exports: $Exports<'node-jsx'>;
}
declare module 'node-jsx/index.js' {
  declare module.exports: $Exports<'node-jsx'>;
}
declare module 'node-jsx/node-jsx.spec.js' {
  declare module.exports: $Exports<'node-jsx/node-jsx.spec'>;
}
declare module 'node-jsx/test-module.js' {
  declare module.exports: $Exports<'node-jsx/test-module'>;
}
declare module 'node-jsx/test-sourcemap.js' {
  declare module.exports: $Exports<'node-jsx/test-sourcemap'>;
}
