// flow-typed signature: 448bdd067e3ac3fc80500a5fa41c8e20
// flow-typed version: <<STUB>>/uswds_v^1.1.0-pre/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uswds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uswds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uswds/build/dist/js/uswds' {
  declare module.exports: any;
}

declare module 'uswds/build/dist/js/uswds.min' {
  declare module.exports: any;
}

declare module 'uswds/build/themes/mandelbrot/js/mandelbrot' {
  declare module.exports: any;
}

declare module 'uswds/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'uswds/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'uswds/dist/js/uswds' {
  declare module.exports: any;
}

declare module 'uswds/dist/js/uswds.min' {
  declare module.exports: any;
}

declare module 'uswds/fractal' {
  declare module.exports: any;
}

declare module 'uswds/src/js/components/accordion' {
  declare module.exports: any;
}

declare module 'uswds/src/js/components/banner' {
  declare module.exports: any;
}

declare module 'uswds/src/js/components/footer' {
  declare module.exports: any;
}

declare module 'uswds/src/js/components/navigation' {
  declare module.exports: any;
}

declare module 'uswds/src/js/components/search' {
  declare module.exports: any;
}

declare module 'uswds/src/js/components/toggle-field-mask' {
  declare module.exports: any;
}

declare module 'uswds/src/js/components/toggle-form-input' {
  declare module.exports: any;
}

declare module 'uswds/src/js/components/validator' {
  declare module.exports: any;
}

declare module 'uswds/src/js/initializers/accordions' {
  declare module.exports: any;
}

declare module 'uswds/src/js/initializers/banner' {
  declare module.exports: any;
}

declare module 'uswds/src/js/initializers/footer' {
  declare module.exports: any;
}

declare module 'uswds/src/js/initializers/forms' {
  declare module.exports: any;
}

declare module 'uswds/src/js/initializers/navigation' {
  declare module.exports: any;
}

declare module 'uswds/src/js/initializers/polyfills' {
  declare module.exports: any;
}

declare module 'uswds/src/js/initializers/search' {
  declare module.exports: any;
}

declare module 'uswds/src/js/initializers/skip-nav' {
  declare module.exports: any;
}

declare module 'uswds/src/js/polyfills/element-hidden' {
  declare module.exports: any;
}

declare module 'uswds/src/js/start' {
  declare module.exports: any;
}

declare module 'uswds/src/js/utils/dispatch' {
  declare module.exports: any;
}

declare module 'uswds/src/js/utils/select' {
  declare module.exports: any;
}

declare module 'uswds/src/js/utils/when-dom-ready' {
  declare module.exports: any;
}

declare module 'uswds/src/js/vendor/html5shiv' {
  declare module.exports: any;
}

declare module 'uswds/src/js/vendor/rem.min' {
  declare module.exports: any;
}

declare module 'uswds/src/js/vendor/respond' {
  declare module.exports: any;
}

declare module 'uswds/src/js/vendor/selectivizr-min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uswds/build/dist/js/uswds.js' {
  declare module.exports: $Exports<'uswds/build/dist/js/uswds'>;
}
declare module 'uswds/build/dist/js/uswds.min.js' {
  declare module.exports: $Exports<'uswds/build/dist/js/uswds.min'>;
}
declare module 'uswds/build/themes/mandelbrot/js/mandelbrot.js' {
  declare module.exports: $Exports<'uswds/build/themes/mandelbrot/js/mandelbrot'>;
}
declare module 'uswds/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'uswds/coverage/lcov-report/prettify'>;
}
declare module 'uswds/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'uswds/coverage/lcov-report/sorter'>;
}
declare module 'uswds/dist/js/uswds.js' {
  declare module.exports: $Exports<'uswds/dist/js/uswds'>;
}
declare module 'uswds/dist/js/uswds.min.js' {
  declare module.exports: $Exports<'uswds/dist/js/uswds.min'>;
}
declare module 'uswds/fractal.js' {
  declare module.exports: $Exports<'uswds/fractal'>;
}
declare module 'uswds/src/js/components/accordion.js' {
  declare module.exports: $Exports<'uswds/src/js/components/accordion'>;
}
declare module 'uswds/src/js/components/banner.js' {
  declare module.exports: $Exports<'uswds/src/js/components/banner'>;
}
declare module 'uswds/src/js/components/footer.js' {
  declare module.exports: $Exports<'uswds/src/js/components/footer'>;
}
declare module 'uswds/src/js/components/navigation.js' {
  declare module.exports: $Exports<'uswds/src/js/components/navigation'>;
}
declare module 'uswds/src/js/components/search.js' {
  declare module.exports: $Exports<'uswds/src/js/components/search'>;
}
declare module 'uswds/src/js/components/toggle-field-mask.js' {
  declare module.exports: $Exports<'uswds/src/js/components/toggle-field-mask'>;
}
declare module 'uswds/src/js/components/toggle-form-input.js' {
  declare module.exports: $Exports<'uswds/src/js/components/toggle-form-input'>;
}
declare module 'uswds/src/js/components/validator.js' {
  declare module.exports: $Exports<'uswds/src/js/components/validator'>;
}
declare module 'uswds/src/js/initializers/accordions.js' {
  declare module.exports: $Exports<'uswds/src/js/initializers/accordions'>;
}
declare module 'uswds/src/js/initializers/banner.js' {
  declare module.exports: $Exports<'uswds/src/js/initializers/banner'>;
}
declare module 'uswds/src/js/initializers/footer.js' {
  declare module.exports: $Exports<'uswds/src/js/initializers/footer'>;
}
declare module 'uswds/src/js/initializers/forms.js' {
  declare module.exports: $Exports<'uswds/src/js/initializers/forms'>;
}
declare module 'uswds/src/js/initializers/navigation.js' {
  declare module.exports: $Exports<'uswds/src/js/initializers/navigation'>;
}
declare module 'uswds/src/js/initializers/polyfills.js' {
  declare module.exports: $Exports<'uswds/src/js/initializers/polyfills'>;
}
declare module 'uswds/src/js/initializers/search.js' {
  declare module.exports: $Exports<'uswds/src/js/initializers/search'>;
}
declare module 'uswds/src/js/initializers/skip-nav.js' {
  declare module.exports: $Exports<'uswds/src/js/initializers/skip-nav'>;
}
declare module 'uswds/src/js/polyfills/element-hidden.js' {
  declare module.exports: $Exports<'uswds/src/js/polyfills/element-hidden'>;
}
declare module 'uswds/src/js/start.js' {
  declare module.exports: $Exports<'uswds/src/js/start'>;
}
declare module 'uswds/src/js/utils/dispatch.js' {
  declare module.exports: $Exports<'uswds/src/js/utils/dispatch'>;
}
declare module 'uswds/src/js/utils/select.js' {
  declare module.exports: $Exports<'uswds/src/js/utils/select'>;
}
declare module 'uswds/src/js/utils/when-dom-ready.js' {
  declare module.exports: $Exports<'uswds/src/js/utils/when-dom-ready'>;
}
declare module 'uswds/src/js/vendor/html5shiv.js' {
  declare module.exports: $Exports<'uswds/src/js/vendor/html5shiv'>;
}
declare module 'uswds/src/js/vendor/rem.min.js' {
  declare module.exports: $Exports<'uswds/src/js/vendor/rem.min'>;
}
declare module 'uswds/src/js/vendor/respond.js' {
  declare module.exports: $Exports<'uswds/src/js/vendor/respond'>;
}
declare module 'uswds/src/js/vendor/selectivizr-min.js' {
  declare module.exports: $Exports<'uswds/src/js/vendor/selectivizr-min'>;
}
